server:
  port: 9992


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dh_project?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ENC(hjMovEvXslkNcBl8O/DATA==)
    password: ENC(15rwtWiFfquvgJpwQsZEZw==)
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.naver.com
    port: 587
    username: ENC(DEcVaQgStkpM3sL2VvQ3jS5lMOOzBcR4jSdQS3LDoyY=)
    password: ENC(n5E7A+TAUGIim46RzqpX3ARJdfgcHkft)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show_sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true



  thymeleaf:
    prefix : classpath:/templates/
    suffix: .html
    cache: false

logging:
  level:
    root: INFO


jwt:
  secret-key: X2NyYXNoX3NlcnZpY2Vfc3VwZXJfc2VjcmV0X2tldF8=