server:
  port: 9991


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dh_project?serverTimezone=UTC&characterEncoding=UTF-8
    username: ENC(ofyU6cXTJW1LzUfQ589kRg==)
    password: ENC(444edSDWzZ6DZIlrUfLn8A==)
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    defer-datasource-initialization: true


  thymeleaf:
    cache: false
#    prefix: classpath:/templates
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#logging:
#  level:
#    org.thymeleaf: DEBUG

