server:
  port: 9991


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dh_project?serverTimezone=UTC&characterEncoding=UTF-8
    username: ENC(XA0gffAsSgHSZJh617nnZQ==)
    password: ENC(qKPAInArJkwfr7UViVRWmA==)
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.naver.com
    port: 587
    username: ENC(tujEgTVMwnxdGrpHVuEQHmWwihdnjxiK6aNAwkqhrlw=)
    password: ENC(LPk7ZlYhGLVf6Eup116wKGT36SgTiAvw)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show_sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true



  thymeleaf:
    prefix : classpath:/templates/
    suffix: .html
    cache: false

logging:
  level:
    root: INFO